name: Deploy Tailwind CSS with DaisyUI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install

      - name: Build Tailwind CSS
        run: |
          echo "@tailwind base; @tailwind components; @tailwind utilities;" > styles.css
          npx tailwindcss -i ./styles.css -o ./output.css

      - name: Deploy generated CSS
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          mv output.css public/output.css  # Ajusta la ruta según tu estructura de proyecto
          git add public/output.css
          git commit -m "Generate Tailwind CSS"
          git push
